[plugin]
version = 2.4.4
name = "system_updater"
description = "Sistema de actualización, backups y tienda de plugins para FSFramework"
min_version = "0.5"
author = "Javier Trujillo"
author_url = "https://github.com/eltictacdicta/fs-framework"
repository_url = "https://github.com/eltictacdicta/system_updater"
version_url = "https://raw.githubusercontent.com/eltictacdicta/system_updater/refs/heads/master/fsframework.ini"
version_url_alt = "https://raw.githubusercontent.com/eltictacdicta/system_updater/refs/heads/main/fsframework.ini"
update_zip_url = "https://github.com/eltictacdicta/system_updater/archive/refs/heads/master.zip"
update_zip_url_alt = "https://github.com/eltictacdicta/system_updater/archive/refs/heads/main.zip"
; Plugin del sistema - crítico para actualizaciones
system = true
; Sin dependencias externas
require = ""
